"""add more indexes to matches

Revision ID: 5aee43fa1221
Revises: baedc2b08a4f
Create Date: 2025-08-19 20:53:32.482717

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '5aee43fa1221'
down_revision: Union[str, Sequence[str], None] = 'baedc2b08a4f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_match_p1_date', 'match', ['player_1_id', 'date'], unique=False)
    op.create_index('idx_match_p2_date', 'match', ['player_2_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_match_p2_date', table_name='match')
    op.drop_index('idx_match_p1_date', table_name='match')
    # ### end Alembic commands ###
