"""add indexes to matches

Revision ID: baedc2b08a4f
Revises: 1f025e83e40c
Create Date: 2025-08-19 20:33:57.741661

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'baedc2b08a4f'
down_revision: Union[str, Sequence[str], None] = '1f025e83e40c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_match_players_date', 'match', ['player_1_id', 'player_2_id', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_match_players_date', table_name='match')
    # ### end Alembic commands ###
