"""add_index

Revision ID: db5ac7dae2a6
Revises: 
Create Date: 2025-07-04 21:10:23.649275

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = 'db5ac7dae2a6'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_match_players_date', 'match', ['player_1_id', 'player_2_id', 'date'], unique=False)
    op.create_index(op.f('ix_match_date'), 'match', ['date'], unique=False)
    op.create_index(op.f('ix_match_player_1_id'), 'match', ['player_1_id'], unique=False)
    op.create_index(op.f('ix_match_player_2_id'), 'match', ['player_2_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_match_player_2_id'), table_name='match')
    op.drop_index(op.f('ix_match_player_1_id'), table_name='match')
    op.drop_index(op.f('ix_match_date'), table_name='match')
    op.drop_index('idx_match_players_date', table_name='match')
    # ### end Alembic commands ###
