"""add index on date to matches

Revision ID: 0ba2dfb80f85
Revises: 5aee43fa1221
Create Date: 2025-08-19 22:57:43.943515

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '0ba2dfb80f85'
down_revision: Union[str, Sequence[str], None] = '5aee43fa1221'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_match_date', 'match', ['date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_match_date', table_name='match')
    # ### end Alembic commands ###
