"""add index on ranking

Revision ID: 116d527390b1
Revises: 0ba2dfb80f85
Create Date: 2025-08-20 18:17:04.322831

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '116d527390b1'
down_revision: Union[str, Sequence[str], None] = '0ba2dfb80f85'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index('idx_ranking_circuit_date', 'ranking', ['circuit', 'date'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ranking_circuit_date', table_name='ranking')
    # ### end Alembic commands ###
