"""add indexes to ranking

Revision ID: 1f025e83e40c
Revises: 
Create Date: 2025-08-19 17:58:35.976521

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel


# revision identifiers, used by Alembic.
revision: str = '1f025e83e40c'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_foreign_key(None, 'match', 'tournament', ['tournament_id'], ['tournament_id'])
    op.create_index('idx_ranking_circuit_date_player', 'ranking', ['circuit', 'date', 'player_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_ranking_circuit_date_player', table_name='ranking')
    op.drop_constraint(None, 'match', type_='foreignkey')
    # ### end Alembic commands ###
