name: CI

on:
  push:
    branches: ["**"]
  pull_request:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  lint-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.13'

      - name: Set up uv
        uses: astral-sh/setup-uv@v3

      - name: Install dependencies (default + dev)
        run: cd backend && uv sync --group dev

      - name: Ruff - Lint
        run: cd backend && uv run ruff check --output-format=github .

      - name: Pytest - Run tests
        run: cd backend && uv run pytest


